# Matrix Factorization Collaborative Filtering

### import dataset

In [1]:
#this notebook follows the tutorial written here: https://medium.com/analytics-vidhya/matrix-factorization-as-a-recommender-system-727ee64683f0
#author's original notebook can be found here: https://medium.com/analytics-vidhya/matrix-factorization-as-a-recommender-system-727ee64683f0

In [4]:
#import required libraries
import pandas as pd
import numpy as np
data = pd.read_csv('MF dataset.csv')
data.head()

,3704,1924,4837,867,2631,5410,1733,3536,780,3312,...,207,5817,4097,4755,3977,1520,4622,2160,2542,1535
0,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,3,0,0,0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,4,0,0,0,5,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,4,0,0,0,0,4,4,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,5,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0

In [6]:
#reduce the dataset a bit
data = data[data.columns[:1000]].loc[range(1,1001)]
data.head()

,3704,1924,4837,867,2631,5410,1733,3536,780,3312,...,1173,3940,1599,1140,1851,4556,4363,864,4026,5841
1,0,3,0,0,0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,4,0
2,0,0,4,0,0,0,5,0,0,0,...,0,0,4,0,0,5,5,4,0,0
3,0,0,0,4,0,0,0,0,4,4,...,0,4,0,5,5,3,0,0,3,5
4,0,0,0,0,5,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,5
5,0,0,0,0,0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### implementation of matrix factorization

In [18]:
#import required libraries
import numpy as np
import pandas as pd
from progressbar import progressbar

#### define matrix factorization function

In [24]:
#R is matrix holding true values, P and Q are the two matrix factors of R, P represents # of columns of P and # of rows of Q
def matrix_factorization(R, P, Q, K, steps=100000, alpha=0.0002, beta=0.02):
    Q = Q.T 
    #Q will be same dimension as P when transposed
    
    #set up iterations, progressbar is handy for tracking for loops that take a while
    for step in progressbar(range(steps)):
        #runs script through number of 'steps', which is # times program runs through process of improvement
        for i in range(len(R)):
            for j in range(len(R[i])):
                #i and j track row num and colum num, respectively. can be used to access any cell in matrix
                if R[i][j]>0: #ensures value is valid
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    #var eij is the difference between true value and prediction - which is achieved by multiplying 
                    #ith row of P and jth row of Q
                    
                    #now perform updating with a simplified gradient descent formula
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
                        
        eR = np.dot(P,Q)
        #need to calculate error to see how well predictions are doing
        e = 0 #error variable 
        
        #calculates the mean squared error for each value and saves it to error variable e
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:], Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j], 2))
        if e < 0.001: #set threshold for training to stop
            break
    return P, Q.T

#### let's try this out on a small scale

In [25]:
#set matrix R
R = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]
R = np.array(R)
#define N, M, K
N = len(R)
M = len(R[0])
K = 2

In [26]:
#set randomized values for P and Q
P = np.random.rand(N,K)
Q = np.random.rand(M,K)

In [27]:
#call function
nP, nQ = matrix_factorization(R, P, Q, K)
nR = np.dot(nP, nQ.T)

100% (100000 of 100000) |################| Elapsed Time: 0:01:27 Time:  0:01:27

In [28]:
nR

array([[4.97693485, 2.9832938 , 3.62617733, 1.00193987],
       [3.98255102, 2.40348481, 3.11966549, 0.99980107],
       [1.00305935, 0.99246505, 5.97934647, 4.97023377],
       [0.99834288, 0.90879642, 4.89132357, 3.98393331],
       [1.16585223, 1.00709437, 4.9850464 , 3.99192336]])